steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta secrets versions access --secret=nec-com-transcrypt-key latest > /secrets/nec-com-transcrypt-key
    volumes:
      - name: 'secrets'
        path: '/secrets'

  - name: 'synapio/pipelines:latest'
    volumes:
      - name: 'secrets'
        path: '/secrets'
    args:
      - '-c'
      - |
      - transcrypt -c aes-256-cbc -p echo "$(cat /secrets/nec-com-transcrypt-key)"

