steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud components update
        # Store the secret is a temporary file
        gcloud beta secrets versions access --secret=nec-com-transcrypt-key latest > key.txt
  - name: synapio/pipelines:latest
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # For getting the secret and pass it to a command/script
        - transcrypt -c aes-256-cbc -p '$(cat /secrets/nec-com-transcrypt-key)'
        ./my-script.sh $(cat my-secret-file.txt)

