steps:
  - name: node
    entrypoint: yarn
    args: ['install']
  - name: node
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta secrets versions access --secret=nec-com-transcrypt-key latest > /secrets/nec-com-transcrypt-key
      - git clone https://github.com/elasticdog/transcrypt.git
      - export TRANSCRYPT_KEY="$(gcloud beta secrets versions access --secret=nec-com-transcrypt-key latest)"
      - ./transcrypt/transcrypt -c aes-256-cbc -p $TRANSCRYPT_KEY
  - name: node
    entrypoint: yarn
    args: ['build.prod']
